In this notebook we merge two DF

### imports

In [1]:
import pandas as pd

import matplotlib as mpl
from matplotlib import pyplot as plt
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'
%matplotlib inline

### load DFs

In [2]:
df_road_loads = pd.read_csv('df_road_loads.csv')
df_station=pd.read_csv('final_stations_data_after_avg.csv')
df_station.drop(columns = df_station.columns[0],axis=1,inplace=True)
df_station

,stationId,Rain,WSmax,WDmax,WS,WD,STDwd,TD,RH,TDmax,TDmin,WS1mm,Ws10mm,Time,year,month,Grad,TG,BP
0,42,0.021678,2.996503,151.769231,2.131469,148.629371,12.666434,9.581818,74.972028,9.709790,9.446853,2.638462,2.338462,1174.783217,2017,1,NaN,NaN,NaN
1,42,0.000000,8.979021,97.650350,5.250350,110.839161,17.653147,5.853147,68.720280,5.988811,5.715385,6.993007,5.611189,1173.083916,2017,2,NaN,NaN,NaN
2,42,0.000000,11.289510,126.552448,8.341259,122.384615,10.611189,14.570629,67.027972,14.681818,14.481119,9.662238,8.705594,1173.832168,2017,3,NaN,NaN,NaN
3,42,0.000000,7.118881,223.664336,4.802098,222.489510,11.277622,14.176224,71.944056,14.344755,14.019580,5.892308,5.098601,1172.811189,2017,4,NaN,NaN,NaN
4,42,0.000000,4.623776,239.034965,3.433566,243.986014,14.434266,19.244056,55.314685,19.452448,19.053846,4.079021,3.706993,1173.615385,2017,5,241.832168,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,343,0.023077,4.104895,145.377622,2.286014,144.461538,17.479021,12.109790,83.000000,12.250350,11.980420,3.051049,2.452448,1173.874126,2022,2,NaN,NaN,NaN
1184,343,0.000000,2.511888,167.930070,1.508392,162.041958,16.726573,12.942657,84.391608,13.104196,12.797902,2.046853,1.656643,1174.125874,2022,3,NaN,NaN,NaN
1185,343,0.000000,3.918881,142.160839,2.061538,138.006993,19.331469,18.306294,61.356643,18.561538,18.057343,2.922378,2.274126,1173.111888,2022,4,NaN,NaN,NaN
1186,343,0.000000,6.276923,238.314685,3.523077,236.755245,17.581119,20.285315,80.783217,20.411189,20.146853,4.688112,3.767832,1173.482517,2022,5,NaN,NaN,NaN
1187,343,0.000000,3.881159,207.971014,2.175362,232.702899,18.018116,22.370290,78.565217,22.543478,22.210870,2.999275,2.370290,1172.057971,2022,6,NaN,NaN,NaN

### merge DFs

we created a dictionary which controls the merging keys of each df(station_id for meteorological data and road name for traffic data)

In [3]:
# key=station_id ; value=name_of_road
# station_id=[42,45,54,178,275,74,79,82,124,208,274,41,44,46,78,106,107,343]

Dict = {42: "דרך 4 קטע 250 מק''מ 195.0 עד ק''מ 200.3 מכניסה לטירת כרמל (דרום) עד מחלף חיפה דרום מקום הצבה 199.0",
        45: "דרך 4 קטע 230 מק''מ 177.4 עד ק''מ 190.8 מצומת פוריידיס עד צומת עתלית מקום הצבה 179.8",
        54: "דרך 4 קטע 84 מק''מ 106.8 עד ק''מ 109.3 ממחלף חולון מזרח עד מחלף השבעה מקום הצבה 108.0",
       178: "דרך 4 קטע 100 מק''מ 110.4 עד ק''מ 112.8 ממחלף גנות עד מחלף מסובים מקום הצבה 112.6",
       275:"דרך 4 קטע 150 מק''מ 122.8 עד ק''מ 130.1 ממחלף מורשה עד צומת רעננה מקום הצבה 130.0",
       74:"דרך 4 קטע 61 מק''מ 92.5 עד ק''מ 100.0 ממחלף יבנה עד מחלף חולות מקום הצבה 98.9",
       79:"דרך 4 קטע 10 מק''מ 51.1 עד ק''מ 55.0 מצומת חבל עזה עד צומת יד מרדכי מקום הצבה 54.7",
       82:"דרך 4 קטע 30 מק''מ 64.6 עד ק''מ 65.8 מצומת ברכיה עד צומת אבא הלל מקום הצבה 65.6",
       124:"דרך 4 קטע 57 מק''מ 85.6 עד ק''מ 87.9 ממחלף אשדוד עד מחלף אשדוד צפון מקום הצבה 86.8",
       208:"דרך 4 קטע 22 מק''מ 63.7 עד ק''מ 64.6 מצומת אשקלון עד צומת ברכיה מקום הצבה 64.5",
        274:"דרך 4 קטע 50 מק''מ 72.0 עד ק''מ 78.0 מצומת אשכולות עד כניסה לאשדוד (דרום) מקום הצבה 72.3",
        44:"דרך 4 קטע 240 מק''מ 190.8 עד ק''מ 195.0 מצומת עתלית עד כניסה לטירת כרמל (דרום) מקום הצבה 191.4",
        46:"דרך 4 קטע 210 מק''מ 162.7 עד ק''מ 167.1 מצומת נחל חדרה עד צומת אור עקיבא מקום הצבה 166.2",
        106:"דרך 4 קטע 310 מק''מ 248.1 עד ק''מ 250.6 מצומת בצת עד כניסה לראש הנקרה צפון מקום הצבה 248.6",
        107:"דרך 4 קטע 180 מק''מ 154.5 עד ק''מ 156.2 מצומת הרא\"ה עד צומת יער חדרה מקום הצבה 154.8",
        343:"דרך 4 קטע 290 מק''מ 234.5 עד ק''מ 240.3 מצומת שמרת עד צומת נהרייה מקום הצבה 234.7"}

we only need the summary of both directions of the road.

In [4]:
df_roads_load_dirct=pd.DataFrame()
df_roads_load_dirct = df_road_loads[df_road_loads["כיוון"] == '0']
df_roads_load_dirct.to_csv("df_roads_load_dirct.csv", index=False
         ,encoding='utf-8-sig')
df_roads_load_dirct

,דרך,כיוון,שנה,חודש,ממוצע יומי באלפים,0,1,2,3,4,...,14,15,16,17,18,19,20,21,22,23
1,דרך 4 קטע 10 מק''מ 51.1 עד ק''מ 55.0 מצומת חבל...,0,2017,11,2.8,16,10,4,4,8,...,187,239,189,174,155,110,84,66,52,26
2,דרך 4 קטע 10 מק''מ 51.1 עד ק''מ 55.0 מצומת חבל...,0,2018,4,3.2,13,6,5,6,7,...,198,251,204,199,208,129,91,74,58,28
3,דרך 4 קטע 10 מק''מ 51.1 עד ק''מ 55.0 מצומת חבל...,0,2019,6,3.5,24,11,6,6,6,...,218,268,228,218,223,143,108,90,77,46
4,דרך 4 קטע 10 מק''מ 51.1 עד ק''מ 55.0 מצומת חבל...,0,2020,7,2.8,29,16,9,9,10,...,160,191,173,139,145,141,117,98,68,47
7,דרך 4 קטע 10 מק''מ 51.1 עד ק''מ 55.0 מצומת חבל...,0,2021,3,3.0,18,10,9,6,7,...,212,240,210,179,158,129,87,76,46,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,דרך 4 קטע 62 מק''מ 100.0 עד ק''מ 102.0 ממחלף ח...,0,2020,12,78.7,1024,685,442,417,606,...,4915,5331,5267,4932,4256,3465,2763,2255,1880,1430
372,דרך 4 קטע 70 מק''מ 103.5 עד ק''מ 105.0 ממחלף ג...,0,2020,12,151.5,2115,1206,741,574,831,...,9348,9666,9794,9465,9190,8424,6894,5389,4113,2958
375,דרך 4 קטע 70 מק''מ 103.5 עד ק''מ 105.0 ממחלף ג...,0,2021,11,156.6,2380,1543,1035,806,1370,...,9497,9817,10010,9900,9805,8455,6988,5491,4408,3199
379,דרך 4 קטע 80 מק''מ 105.0 עד ק''מ 106.8 ממחלף ר...,0,2021,8,196.0,4595,2861,1743,1326,2178,...,11078,11627,11378,11268,11168,10426,9666,8819,6876,5212
383,דרך 4 קטע 84 מק''מ 106.8 עד ק''מ 109.3 ממחלף ח...,0,2020,12,124.5,1390,823,538,319,424,...,8151,8067,7786,7333,7212,6725,5245,4339,3313,2073

Now we marge two DFs to one

In [5]:
df_station["avg_month_road_loads"]=None
df_station["dirct_road_loads"]=None
df_station_copy=df_station.copy()

for index,row in df_roads_load_dirct.iterrows():
    road_row=row
    if road_row["דרך"] in Dict.values():
        station_id = [k for k, v in Dict.items() if v == road_row["דרך"]][0]
        df_station_copy = df_station_copy[df_station_copy['stationId'] == station_id]
        for ind in df_station_copy.index:
            current_roads_df_year_int=int(row["שנה"])
            current_roads_df_month_int=int(row["חודש"])
            current_stationId_df_year_int=int(df_station_copy["year"][ind])
            current_stationId_df_month_int=int(df_station_copy["month"][ind])
            if current_stationId_df_year_int== current_roads_df_year_int and current_stationId_df_month_int == current_roads_df_month_int:
#                 print(station_id,current_stationId_df_year_int,current_stationId_df_month_int,row["כיוון"])
                df_station["avg_month_road_loads"][ind]=row["ממוצע יומי באלפים"]
                df_station["dirct_road_loads"][ind]=row["כיוון"]
        df_station_copy=df_station.copy()

In [6]:
df_station

,stationId,Rain,WSmax,WDmax,WS,WD,STDwd,TD,RH,TDmax,...,WS1mm,Ws10mm,Time,year,month,Grad,TG,BP,avg_month_road_loads,dirct_road_loads
0,42,0.021678,2.996503,151.769231,2.131469,148.629371,12.666434,9.581818,74.972028,9.709790,...,2.638462,2.338462,1174.783217,2017,1,NaN,NaN,NaN,None,None
1,42,0.000000,8.979021,97.650350,5.250350,110.839161,17.653147,5.853147,68.720280,5.988811,...,6.993007,5.611189,1173.083916,2017,2,NaN,NaN,NaN,None,None
2,42,0.000000,11.289510,126.552448,8.341259,122.384615,10.611189,14.570629,67.027972,14.681818,...,9.662238,8.705594,1173.832168,2017,3,NaN,NaN,NaN,None,None
3,42,0.000000,7.118881,223.664336,4.802098,222.489510,11.277622,14.176224,71.944056,14.344755,...,5.892308,5.098601,1172.811189,2017,4,NaN,NaN,NaN,None,None
4,42,0.000000,4.623776,239.034965,3.433566,243.986014,14.434266,19.244056,55.314685,19.452448,...,4.079021,3.706993,1173.615385,2017,5,241.832168,NaN,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,343,0.023077,4.104895,145.377622,2.286014,144.461538,17.479021,12.109790,83.000000,12.250350,...,3.051049,2.452448,1173.874126,2022,2,NaN,NaN,NaN,None,None
1184,343,0.000000,2.511888,167.930070,1.508392,162.041958,16.726573,12.942657,84.391608,13.104196,...,2.046853,1.656643,1174.125874,2022,3,NaN,NaN,NaN,None,None
1185,343,0.000000,3.918881,142.160839,2.061538,138.006993,19.331469,18.306294,61.356643,18.561538,...,2.922378,2.274126,1173.111888,2022,4,NaN,NaN,NaN,None,None
1186,343,0.000000,6.276923,238.314685,3.523077,236.755245,17.581119,20.285315,80.783217,20.411189,...,4.688112,3.767832,1173.482517,2022,5,NaN,NaN,NaN,None,None
1187,343,0.000000,3.881159,207.971014,2.175362,232.702899,18.018116,22.370290,78.565217,22.543478,...,2.999275,2.370290,1172.057971,2022,6,NaN,NaN,NaN,None,None

we are dropping mismatched rows after merging

In [7]:
df_stations_and_traffic_marged=df_station.copy()
df_stations_and_traffic_marged = df_stations_and_traffic_marged[df_stations_and_traffic_marged['dirct_road_loads'].notna()]
df_stations_and_traffic_marged.drop(['Time'], axis=1, inplace=True) 
df_stations_and_traffic_marged

,stationId,Rain,WSmax,WDmax,WS,WD,STDwd,TD,RH,TDmax,TDmin,WS1mm,Ws10mm,year,month,Grad,TG,BP,avg_month_road_loads,dirct_road_loads
55,42,0.000000,7.282857,241.885714,5.475000,240.657143,10.381429,NaN,NaN,NaN,NaN,6.315714,5.661429,2021,8,NaN,NaN,NaN,40.4,0
84,45,0.000000,5.318182,273.104895,2.844755,283.027972,19.444755,25.118881,71.447552,25.281818,24.948252,3.954545,3.059441,2018,7,NaN,NaN,NaN,15.0,0
100,45,0.000000,3.578322,223.258741,2.140559,220.286713,14.280420,20.940559,73.153846,21.052448,20.830070,2.841259,2.290909,2019,11,NaN,NaN,NaN,14.8,0
107,45,0.000000,4.314685,230.650350,2.432867,224.475524,19.653147,21.137762,65.482517,21.288811,20.986713,3.306294,2.625175,2020,6,NaN,NaN,NaN,15.9,0
121,45,0.000000,3.914493,236.789855,2.306522,235.811594,15.929710,27.294928,75.862319,27.429710,27.148551,3.098551,2.463768,2021,8,NaN,NaN,NaN,15.8,0
179,54,0.000000,2.188811,152.440559,1.460839,154.594406,12.655944,15.897203,76.398601,16.033566,15.757343,1.896503,1.623077,2020,12,NaN,16.401399,1008.696503,124.5,0
245,178,0.000000,3.888112,156.167832,2.830769,164.818182,8.923776,17.841958,68.335664,17.953147,17.738462,3.328671,2.979021,2020,12,NaN,NaN,NaN,179.8,0
253,178,0.000000,3.142029,227.115942,2.142029,228.768116,12.376087,28.844928,67.804348,28.960145,28.739130,2.646377,2.256522,2021,8,NaN,NaN,NaN,222.5,0
311,275,0.000000,NaN,NaN,NaN,NaN,NaN,17.562369,71.547038,NaN,NaN,NaN,NaN,2020,12,NaN,NaN,NaN,99.8,0
319,275,0.000000,NaN,NaN,NaN,NaN,NaN,28.641155,70.429603,NaN,NaN,NaN,NaN,2021,8,NaN,NaN,NaN,92.8,0
377,74,0.000000,NaN,NaN,NaN,NaN,NaN,16.342657,73.153846,16.477622,16.220280,NaN,NaN,2020,12,NaN,16.725175,NaN,130.7,0
383,74,0.000000,NaN,NaN,NaN,NaN,NaN,24.088811,73.013986,24.247552,23.934266,NaN,NaN,2021,6,NaN,26.662937,NaN,154.2,0
406,79,0.000000,3.487413,184.545455,1.915385,192.048951,18.612587,20.557343,68.013986,20.765734,20.364336,2.702797,2.115385,2017,11,189.958042,24.376224,NaN,2.8,0
411,79,0.000000,3.217483,195.538462,1.797203,199.398601,18.201399,16.979720,80.678322,17.190909,16.774825,2.513287,1.988811,2018,4,268.678322,18.792308,NaN,3.2,0
425,79,0.000000,3.672727,252.237762,2.016783,254.286713,19.216084,25.051049,72.244755,25.295804,24.820979,2.858042,2.212587,2019,6,344.034965,28.494406,NaN,3.5,0
438,79,0.000000,3.868531,219.048951,2.010490,220.748252,19.917483,25.151049,77.006993,25.339161,24.972727,2.918182,2.186713,2020,7,344.643357,28.996503,NaN,2.8,0
446,79,0.000000,4.704895,203.608392,3.037063,204.307692,11.977622,13.081818,80.062937,13.240559,12.937063,3.760140,3.198601,2021,3,168.132867,13.761538,NaN,3.0,0
462,82,0.000000,3.025175,178.671329,2.104895,180.055944,11.503497,10.749650,73.174825,10.928671,10.567133,2.639161,2.318182,2017,1,155.776224,10.504895,NaN,40.5,0
477,82,0.000000,3.198601,220.657343,2.085315,232.825175,12.411888,17.098601,75.685315,17.312587,16.894406,2.709091,2.269930,2018,4,276.097902,18.891608,NaN,45.6,0
492,82,0.000000,4.249650,246.125874,2.763636,242.426573,14.382517,26.582517,73.797203,26.786014,26.398601,3.550350,2.952448,2019,7,330.692308,29.573427,NaN,48.3,0
500,82,0.002797,8.151748,253.391608,5.646853,253.678322,8.739161,14.062937,77.139860,14.251748,13.869231,6.869930,5.998601,2020,3,139.419580,14.080420,NaN,35.8,0
581,124,0.000000,NaN,NaN,NaN,NaN,NaN,24.382517,77.384615,24.518881,24.243357,NaN,NaN,2021,6,NaN,NaN,NaN,136.1,0
594,208,0.000000,4.293706,189.104895,3.039860,187.888112,11.488811,11.637762,68.475524,11.827972,11.457343,3.705594,3.257343,2017,1,NaN,NaN,NaN,51.2,0
609,208,0.000000,5.269231,147.517483,4.260839,144.965035,8.861538,17.617483,81.433566,17.793706,17.463636,4.843357,4.458042,2018,4,NaN,NaN,NaN,52.1,0
624,208,0.000000,5.660839,193.279720,4.544056,207.356643,8.404895,27.055944,80.034965,27.237063,26.895804,5.158042,4.718881,2019,7,NaN,NaN,NaN,51.6,0
635,208,0.000000,5.501399,141.335664,4.427972,147.048951,8.288811,21.346154,73.279720,21.506294,21.207692,4.996503,4.625874,2020,6,NaN,NaN,NaN,49.6,0
660,274,0.000000,2.116783,153.517483,1.101399,155.594406,16.251049,10.772028,77.482517,10.955245,10.597902,1.655944,1.282517,2017,1,NaN,NaN,NaN,70.1,0
675,274,0.000000,3.100000,200.762238,1.572028,197.475524,19.793007,16.858042,82.321678,17.132168,16.590909,2.309091,1.752448,2018,4,NaN,NaN,NaN,68.2,0
694,274,0.000000,2.176224,170.223776,0.976224,171.048951,25.100699,20.269231,79.475524,20.497203,20.044755,1.491608,1.095105,2019,11,NaN,NaN,NaN,66.4,0
701,274,0.000000,3.373427,168.734266,1.720280,164.279720,24.331469,21.431469,67.020979,21.680420,21.191608,2.455245,1.881818,2020,6,NaN,NaN,NaN,64.4,0
710,274,0.009790,3.703497,181.258741,2.222378,184.321678,14.579720,13.248252,85.664336,13.397902,13.077622,2.924476,2.418182,2021,3,NaN,NaN,NaN,86.3,0
802,44,0.004196,2.851049,192.727273,1.534965,192.132867,19.518182,19.751049,70.272727,19.937762,19.561538,2.297203,1.743357,2017,11,NaN,21.583916,NaN,15.9,0
805,44,0.000000,2.743357,128.944056,1.466434,123.937063,22.740559,12.274825,75.440559,12.483217,12.072727,2.175524,1.651748,2018,2,NaN,12.616084,NaN,16.2,0
826,44,0.000000,2.949650,166.272727,1.688112,167.356643,18.204895,20.511888,77.979021,20.706993,20.304895,2.353147,1.868531,2019,11,NaN,21.886713,NaN,16.3,0
834,44,0.000000,3.957343,214.636364,2.167133,214.538462,18.725874,24.821678,77.279720,25.044056,24.620280,3.079021,2.353846,2020,7,NaN,29.909790,NaN,13.7,0
847,44,0.000000,3.047101,184.224638,1.588406,180.434783,16.955797,28.305797,74.521739,28.476812,28.126812,2.372464,1.758696,2021,8,NaN,32.448551,NaN,16.8,0
869,46,0.000000,5.556643,62.027972,3.961538,61.356643,9.350350,18.929371,52.489510,19.076923,18.785315,4.703497,4.186014,2017,12,NaN,NaN,NaN,36.4,0
873,46,0.000000,6.169930,143.447552,4.979720,124.727273,15.432168,17.855944,85.027972,17.986713,17.722378,5.646853,5.234965,2018,4,NaN,NaN,NaN,36.1,0
889,46,0.000000,4.556643,292.622378,3.357343,288.734266,10.196503,27.841958,72.440559,27.906993,27.781818,4.108392,3.548951,2019,8,NaN,NaN,NaN,38.1,0
896,46,0.009790,10.171329,283.433566,7.904895,281.937063,6.655245,15.671329,67.916084,15.802797,15.541958,9.110490,8.253846,2020,3,NaN,NaN,NaN,36.8,0
906,46,0.000000,5.486713,69.713287,3.756643,70.146853,10.211888,17.555245,63.202797,17.664336,17.450350,4.553846,3.979720,2021,1,NaN,NaN,NaN,26.0,0
991,106,0.000000,8.778322,153.405594,5.462238,146.888112,13.662238,8.860839,57.027972,9.026573,8.698601,7.148951,5.870629,2017,2,NaN,NaN,NaN,3.8,0
1013,106,0.011888,6.371329,128.391608,4.704895,129.643357,7.544755,16.926573,81.823529,17.066434,16.790210,5.506993,4.909091,2018,12,NaN,NaN,NaN,4.0,0
1020,106,0.000000,7.697203,172.412587,5.325874,152.314685,10.992308,27.906294,66.650350,28.067832,27.760839,6.441259,5.544755,2019,7,NaN,NaN,NaN,4.9,0
1047,106,0.000000,6.443357,156.650350,4.559441,159.111888,9.593706,24.409091,76.447552,24.516783,24.296503,5.473427,4.764336,2021,10,NaN,NaN,NaN,5.0,0
1066,107,0.002098,NaN,NaN,NaN,NaN,NaN,20.111189,67.391608,20.288112,19.928671,NaN,NaN,2017,11,NaN,21.655944,NaN,39.1,0
1069,107,0.000000,NaN,NaN,NaN,NaN,NaN,11.221678,75.125874,11.385315,11.054545,NaN,NaN,2018,2,NaN,12.103497,NaN,35.0,0
1083,107,0.083916,NaN,NaN,NaN,NaN,NaN,13.789510,89.426573,13.905594,13.672028,NaN,NaN,2019,4,NaN,14.492308,NaN,36.4,0
1094,107,0.030769,NaN,NaN,NaN,NaN,NaN,14.476923,80.790210,14.637762,14.332867,NaN,NaN,2020,3,NaN,15.094406,NaN,43.2,0
1104,107,0.000000,NaN,NaN,NaN,NaN,NaN,15.245455,74.076923,15.449650,15.047552,NaN,NaN,2021,1,NaN,13.651748,NaN,43.3,0
1116,107,0.027972,NaN,NaN,NaN,NaN,NaN,14.792308,78.986014,14.869930,14.717483,NaN,NaN,2022,1,NaN,14.424476,NaN,40.8,0
1127,343,0.000000,4.017483,245.811189,2.486713,247.349650,19.316783,21.662238,71.958042,21.957343,21.352448,3.333566,2.679021,2017,6,NaN,NaN,NaN,58.7,0
1145,343,0.010490,5.206294,144.363636,2.986713,143.664336,14.376224,16.023077,86.874126,16.165734,15.891608,3.887413,3.171329,2018,12,NaN,NaN,NaN,57.4,0
1152,343,0.000000,5.790210,147.874126,3.418881,132.559441,14.421678,28.097902,66.930070,28.316084,27.887413,4.523776,3.620979,2019,7,NaN,NaN,NaN,60.2,0
1164,343,0.000000,4.049650,221.055944,2.389510,225.699301,18.836364,24.953147,75.370629,25.179021,24.720280,3.253147,2.573427,2020,7,NaN,NaN,NaN,53.4,0
1179,343,0.000000,4.228671,135.307692,2.423776,131.923077,15.836364,24.111888,75.195804,24.253147,23.969930,3.255245,2.592308,2021,10,NaN,NaN,NaN,69.1,0

<u>**Columns:**</u>

* **StationId -** Id of station
* **Rain -** amount of rain, mm
* **WSmax -** top wind speed, m/s
* **WDmax -** direction of the top breeze, deg
* **WS -** wind speed, m/s
* **WD -** wind direction, deg
* **STDwd -** Standard deviation of wind direction,deg
* **RH -** relative humidity, %
* **TDmax -** Maximum temperature, &deg;c
* **TDmin -** Minimum temperature, &deg;c
* **WS1mm -** Maximum minute wind speed, m/s
* **Ws10mm -** maximum wind speed 10 minutes, m/s
* **year -** year
* **month -** month
* **Grad -** Global radiation, w/m2
* **TD -** air temperature, w/m2
* **TG-** ground temperature, w/m2
* **BP -**  pressure in Station Comments w/m2
* **avg_month_road_loads -** Average traffic of this month, in thousands
* **dirct_road_loads -**  
   - 0: Traffic in both directions.
   - 1:  The traffic to...
   - 2: The traffic from...

In [8]:
df_stations_and_traffic_marged.to_csv("df_stations_and_traffic_marged.csv")